# Generated by Django 5.1.1 on 2024-10-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderLink',
        ),
    ]
