# Generated by Django 5.1.1 on 2024-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bioeducar_app', '0004_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('criador', models.CharField(max_length=100)),
                ('licenca', models.CharField(max_length=100)),
            ],
        ),
    ]
