# Generated by Django 5.1.1 on 2024-10-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='criador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='licenca',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
