# Generated by Django 5.1.1 on 2024-10-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0006_alter_image_criador_alter_image_licenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='nome',
        ),
    ]
