# Generated by Django 5.1.1 on 2024-10-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0008_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
