# Generated by Django 5.1.1 on 2024-10-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0009_delete_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('pagina', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=2)),
                ('topico', models.CharField(max_length=50)),
            ],
        ),
    ]
