# Generated by Django 5.1.1 on 2024-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0010_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
