# Generated by Django 5.1.1 on 2024-10-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0011_text_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='title',
            new_name='titulo',
        ),
    ]
