# Generated by Django 5.1.1 on 2024-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0012_rename_title_text_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='titulo',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
