# Generated by Django 5.1.1 on 2024-10-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0013_alter_text_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
