# Generated by Django 5.1.1 on 2024-10-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0014_alter_text_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='topico',
            new_name='identifier',
        ),
    ]
