# Generated by Django 5.1.1 on 2024-10-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioeducar_app', '0015_rename_topico_text_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
